server.port: 8081
spring:
  liquibase:
    url: jdbc:postgresql://localhost:5433/marginal
    user: test
    password: testpass
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5433/marginal
    username: test
    password: testpass
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
kafka:
  bootstrapAddress: localhost:9092
  producer-id: medicine_id

bot:
  token: "5731557838:AAFKKSiuCTgeIM3YKJv5ZWvGV0WHeXfkR5A"
