server.port: 8081
spring:
  liquibase:
    url: jdbc:postgresql://localhost:5433/marginal
    user: test
    password: testpass
  datasource:
    url: jdbc:postgresql://localhost:5433/marginal
    username: test
    password: testpass
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
kafka:
  bootstrapAddress: localhost:9092
  producer-id: medicine_id
